### ISSUE TITLE
You can run this for the whole application?

### ISSUE THREAD

**Issue by mhosman** [morrisjdev/ng-webworker-helper#1]
The idea is to run all the application in a webworker in order to let only animations to run under the main thread.

**Comment by morrisjdev** [comment]
You're right that this is the idea of the webworker implementation Angular delivers. But if you only want to run a part of CPU intensive tasks in a seperate thread you have to handle it by yourself. Also if you have an existing application and access DOM objects from functions e.g. in a component you could also encounter problems. This is the idea of this helper.

**Comment by mhosman** [comment]
Yes but the usage description is only to run funcions in a web-worker, not the whole application.

**Comment by morrisjdev** [comment]
Sorry for the late reply. To run the whole application check out angular platform-webworker.

But the problem of using platform-webworker is, that it runs all the code in a WebWorker thread. If you have an application and access the Dom you maybe will get problems. And this is the reason why I wrote this small library.

**Comment by mhosman** [comment]
Thanks for your response. The main problem is that when a module is loading, the ui is being blocked (loaders stucked for a second). I can't find a good way to achieve this. Thanks!
